# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('address', models.CharField(max_length=200, null=True)),
                ('length_of_stay', models.CharField(choices=[('Less than 6 months', 'Less than 6 months'), ('6 months', '6 months'), ('10 months', '10 months'), ('1 year', '1 year'), ('2 plus years', '2 plus years')], max_length=20, null=True)),
                ('move_in_condition', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=5, null=True)),
                ('apartment_condition', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=5, null=True)),
                ('maintenance_efficiency', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=5, null=True)),
                ('treatment_by_your_landlord', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=5, null=True)),
                ('communication_with_your_landlord', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=5, null=True)),
                ('landlord_helpfulness', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=5, null=True)),
                ('overall_rating', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=5, null=True)),
                ('rent_again', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradethelandlord.Landlord')),
            ],
        ),
    ]
