# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradethelandlord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='apartment_condition',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='communication_with_your_landlord',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='landlord_helpfulness',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='maintenance_efficiency',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='move_in_condition',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='overall_rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='treatment_by_your_landlord',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5, null=True),
        ),
    ]
