# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradethelandlord', '0002_auto_20180310_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='length_of_stay',
            field=models.CharField(choices=[('Less than 6 months', 'Less than 6 months'), ('6 months', '6 months'), ('10 months', '10 months'), ('1 year', '1 year'), ('2 plus years', '2 plus years')], max_length=20),
        ),
    ]
