# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradethelandlord', '0005_auto_20180410_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='address',
            field=models.CharField(default='Address', max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='apartment_condition',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=5),
        ),
    ]
