# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-16 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradethelandlord', '0007_auto_20180410_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='additional_comments',
        ),
        migrations.AlterField(
            model_name='review',
            name='apartment_condition',
            field=models.CharField(choices=[('Very dissatisfied', 'Very dissatisfied'), ('Somewhat dissatisfied', 'Somewhat dissatisfied'), ('Neither satisfied nor dissatisfied', 'Neither satisfied nor dissatisfied'), ('Somewhat satisfied', 'Somewhat satisfied'), ('Very satisfied', 'Very satisfied')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='communication_with_your_landlord',
            field=models.CharField(choices=[('Very dissatisfied', 'Very dissatisfied'), ('Somewhat dissatisfied', 'Somewhat dissatisfied'), ('Neither satisfied nor dissatisfied', 'Neither satisfied nor dissatisfied'), ('Somewhat satisfied', 'Somewhat satisfied'), ('Very satisfied', 'Very satisfied')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='landlord_helpfulness',
            field=models.CharField(choices=[('Not at all helpful', 'Not at all helpful'), ('Not so helpful', 'Not so helpful'), ('Somewhat helpful', 'Somewhat helpful'), ('Very helpful', 'Very helpful'), ('Extremely helpful', 'Extremely helpful')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='length_of_stay',
            field=models.CharField(choices=[('Less than 6 months', 'Less than 6 months'), ('6 months', '6 months'), ('10 months', '10 months'), ('12 months', '12 months'), ('12 plus months', '12 plus months')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='maintenance_efficiency',
            field=models.CharField(choices=[('Very dissatisfied', 'Very dissatisfied'), ('Somewhat dissatisfied', 'Somewhat dissatisfied'), ('Neither satisfied nor dissatisfied', 'Neither satisfied nor dissatisfied'), ('Somewhat satisfied', 'Somewhat satisfied'), ('Very satisfied', 'Very satisfied')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='move_in_condition',
            field=models.CharField(choices=[('Very dissatisfied', 'Very dissatisfied'), ('Somewhat dissatisfied', 'Somewhat dissatisfied'), ('Neither satisfied nor dissatisfied', 'Neither satisfied nor dissatisfied'), ('Somewhat satisfied', 'Somewhat satisfied'), ('Very satisfied', 'Very satisfied')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='overall_rating',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='treatment_by_your_landlord',
            field=models.CharField(choices=[('Very dissatisfied', 'Very dissatisfied'), ('Somewhat dissatisfied', 'Somewhat dissatisfied'), ('Neither satisfied nor dissatisfied', 'Neither satisfied nor dissatisfied'), ('Somewhat satisfied', 'Somewhat satisfied'), ('Very satisfied', 'Very satisfied')], default='1', max_length=5),
        ),
    ]
